[build]
  publish = "FRONTEND"

[dev]
  publish = "FRONTEND"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify configuration
[[redirects]]
  from = "/api/*"
  to = "https://froggle3-0.onrender.com/api/:splat"
  status = 200
  force = true 